version: '3.3'
services:
  tomcat:
    image: tomcat:jdk14-openjdk-oracle
    container_name: tomcat-jdk14-openjdk-oracle
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:8080
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./conf:/usr/local/tomcat/conf
