version: '3.3'
services:
  oracle-11g:
    image: jaspeen/oracle-11g
    container_name: oracle-11g
    restart: always
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 1521:1521
    volumes:
      - ./install:/install
      - ./dpdump:/opt/oracle/dpdump

# dbuser: SYS/oracle
