version: '3.3'
services:
  oracle-11g:
    image: loliconneko/oracle-ee-11g
    container_name: oracle-11g
    privileged: true
    restart: always
    environment:
      ORACLE_SID: "EE"
      service name: "ORCL"
      WEB_CONSOLE: false
      DBCA_TOTAL_MEMORY: "1024"
    ports:
      - 15211:1521
    volumes:
      - ./data:/u01/app/oracle
