version: '3.3'
services:
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:ubuntu-latest
    container_name: zabbix-server-mysql-ubuntu-latest
    restart: always
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    cap_add:
      - ALL
    environment:
      TZ: "Asia/Shanghai"
      ZBX_CACHESIZE: "4096M"
      DB_SERVER_HOST: "192.168.0.200"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbix"
    ports:
      - 10051:10051
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./datas/zabbix:/etc/zabbix
      - ./datas/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-latest
    container_name: zabbix-web-nginx-mysql-ubuntu-latest
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      DB_SERVER_HOST: "192.168.0.200"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbix"
      ZBX_SERVER_NAME: "192.168.0.200"
      PHP_TZ: "Asia/Shanghai"
    ports:
      - 60001:8080
    depends_on:
      - zabbix-server-mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-latest
    container_name: zabbix-agent-ubuntu-latest
    privileged: true
    restart: always
    cap_add:
      - ALL
    volumes:
      - /etc/timezone:/etc/timezone
    environment:
      ZBX_SERVER_HOST: zabbix-server-mysql
    ports:
      - 10050:10050
