version: "3.3"
services:
  openssh-server:
    image: linuxserver/openssh-server
    container_name: openssh-server
    hostname: txl-openssh-server #optional
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      #- PUBLIC_KEY=yourpublickey #optional
      #- PUBLIC_KEY_FILE=/path/to/file #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=passwd #optional
      - USER_PASSWORD_FILE=/path/to/file #optional
      - USER_NAME=username #optional
    volumes:
      - ./config:/config
      - ./etc:/etc
      - ./datas:/defaults
    ports:
      - 2222:2222