version: '3.3'
services:
  agreement:
    image: txl/agreement:2.0.0
    container_name: txl-agreement
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 9090:9090
 #   volumes:
 #    - ./data:/mount
