version: '3.3'
services:
  registry:
    image: registry
    restart: always
    container_name: docker-registry
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    container_name: docker-registry-frontend
    ports:
      - 9001:80
    volumes:
      - ./certs/frontend.crt:/etc/apache2/server.crt:ro
      - ./certs/frontend.key:/etc/apache2/server.key:ro
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.1.241
      - ENV_DOCKER_REGISTRY_PORT=5000